function img = getMorphFace(bImg)
img_conn = connection_comp(bImg,15);
% figure;
% imshow(img_conn);
img2d = dilation(img_conn);
% figure;
% imshow(img2d);
img2d_conn = connection_comp(img2d,40);
% figure;
% imshow(img2d_conn);
img2e = erosion(img2d_conn);
% figure;
% imshow(img2e);
% img2dd = dilation(img2d_conn);
img2e_conn = connection_comp(img2e,80);
% figure;
% imshow(img2e_conn);
% img2e = erosion(BinarizedFaceImage);
img2ee = erosion(img2e_conn);
% figure;
% imshow(img2ee);
img2ee_conn = connection_comp(img2ee,12);
% figure;
% imshow(img2ee_conn);
img22d = dilation(dilation(img2ee_conn));
% figure;
% imshow(img22d);
% figure;
img = img22d;