%task1
%generate the clusters of face pixels for face1.jpg
close all;
testImg = imread('face1.jpg');
url = imread('training_face_image/train15.jpg');
FaceModel = getFaceModel(url);
BinarizedFaceImage = getBinarizedFaceImage(testImg,FaceModel);
figure;
imshow(BinarizedFaceImage);
FinalFaceImage = getMorphFace(BinarizedFaceImage);
figure;
imshow(FinalFaceImage);
%generate the clusters of face pixels for face2.jpg
 close all;
 testImg2 = imread('face2.jpg');
 url2 = imread('training_face_image/train10.jpg');
 FaceModel2 = getFaceModel(url2);
 BinarizedFaceImage2 = getBinarizedFaceImage(testImg2,FaceModel2);
 figure;
 imshow(BinarizedFaceImage2);
FinalFaceImage2 = getMorphFace(BinarizedFaceImage2);
figure;
imshow(FinalFaceImage2);
% img_conn_2 = connection_comp(BinarizedFaceImage2,300);
% figure;
% imshow(img_conn_2);
% img2_2e = erosion(img_conn_2);
% figure;
% imshow(img2_2e);
% img2_conn_2e = connection_comp(img2_2e,300);
% figure;
% imshow(img2_conn_2e);
% img2_2ee = erosion(img2_conn_2e);
% figure;
% imshow(img2_2ee);
% img2_conn_2ee = erosion(img2_2ee);
% figure;
% imshow(img2_conn_2ee);
% img2_conn2_2ee = connection_comp(img2_conn_2ee,300);
% figure;
% imshow(img2_conn2_2ee);
